-- Remove the constraint that limits task types to 'study' or 'algorithm'
-- This allows new types like 'project', 'other', etc. generated by AI
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_type_check;
